version: "3"

services:
  web:
    container_name: jadon-interview-test-client
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - test-network

networks:
  test-network:
    external:
      name: server_test-network